name: Python Uppercase

on:
    push:
        paths:
            - ".github/workflows/python-uppercase.yml"
            - "py-upper/**"
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout python version
              run: python --version
            - name: Dusplay current directory
              run: pwd
            - name: List files in current directory
              run: ls -R
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: List files in repository
              run: ls -R
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.13'
            - name: display Python version
              run: python --version
            - name: Install dependencies
              uses: py-actions/py-dependency-install@v4
              with:
                  path: py-upper/requirements.txt  
                  update-pip: true
            - name: Run Python tests
              working-directory: py-upper
              run: pytest -v
            - name: Check docker version
              run: docker --version