# This is a basic workflow to help you get started with Actionss

name: Simplee Demo

# Controls when the workflow will run
on:
  push:
    
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  schedule:
    - cron: "*/5 * * * *"
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
     customer:
       description: 'Customer name'
       required: true
       default: 'Default Customer'
       type: choice
       options:
         - Default Customer
         - Customer A
         - Customer B
         - Customer C
     operator_name:
       description: 'Operator name'
       required: true
       default: 'Default Operator'
       type: string
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_my_app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Go sleep for 10 seconds
        run: |
          echo "Sleeping for 10 seconds..."
          sleep 10
          echo "Awake now!"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: TEst input parameters
        run: |
          echo "Customer: $CUSTOMER"
          echo "Operator Name: $OPERATOR_NAME"
        env:
          CUSTOMER: ${{ github.event.inputs.customer }}
          OPERATOR_NAME: ${{ github.event.inputs.operator_name }}